steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '-t',
        'southamerica-west1-docker.pkg.dev/conexia-486401/conexia-registry/api-gateway',
        '-f',
        'api-gateway/Dockerfile.prod',
        '--platform=linux/amd64',
        'api-gateway',
      ]

  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'push',
        'southamerica-west1-docker.pkg.dev/conexia-486401/conexia-registry/api-gateway',
      ]

options:
  logging: CLOUD_LOGGING_ONLY
