FROM postgres:16.5-alpine

# Copiar script de configuración
COPY postgres-init/03-setup-auth.sh /docker-entrypoint-initdb.d/03-setup-auth.sh

# Configurar variables de entorno
ENV POSTGRES_HOST_AUTH_METHOD=trust

# Exponer puerto
EXPOSE 5432 