FROM postgres:16.5-alpine

# Copiar scripts de inicialización
COPY postgres-init/ /docker-entrypoint-initdb.d/

# Hacer ejecutables los scripts
RUN chmod +x /docker-entrypoint-initdb.d/*.sh

# Configurar variables de entorno
ENV POSTGRES_HOST_AUTH_METHOD=trust

# Exponer puerto
EXPOSE 5432 